### PR TITLE
Date changes for 2018 and staff updates for 2017

### PR DESCRIPTION
**Pull request by maanavsa**

### CODE REVIEW

**Comment by maanavsa** [comment]
resolved photo pixel changes. is there still an issue with the rows?

**Comment by allejo** [comment]
The pictures should be .jpg extension (and lower case)

See here: https://github.com/CityofSantaMonica/youthtechprogram/blob/gh-pages/_pages/index/_program-staff.html#L14

image

**Comment by thekaveman** [comment]
:rofl: that last commit @allejo :rofl:

**Comment by allejo** [comment]
@thekaveman 😄 

@maanavsa thanks for all the changes! the row issue was fixed in cbefa5a1d7b0f4351bdbded314e766be2df5f29b to be more _flex_-ible so it shouldn't be an issue any more

**Pull request merged**
